[package]
name = "rust-send"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
